import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BD Martyr's 2024npm",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
         <Nav/>
        </header>
        <main>
        {children}
        </main>
    <footer>
<Footer/>
    </footer>
        </body>
    </html>
  );
}
